kind: PersistentVolume
apiVersion: v1
metadata:
  name: monpv-ubuntu
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/pvdata-unbuntu"