apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu-ssh
    image: ubuntu
    env:
    - name: PASSWORD
      value: password
    - name: USER
      value: value
    command: ["bash", "-c", "apt-get update && apt-get install -y sudo && apt-get install -y openssh-server && useradd -m user && echo 'user:$(PASSWORD)' | chpasswd && usermod -aG sudo user && service ssh start && tail -f /dev/null"]
    ports:
    - containerPort: 22
    stdin: true
    tty: true
    
