apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssh-ingress
  namespace: 3y87k1dawhvho8sy8bowc8
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
    - host: ssh.serveroo.fr
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ssh-service
                port:
                  number: 22