apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-name
  labels:
    app: ubuntu-app
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    env:
    - name: PASSWORD
      value: password
    - name: USER
      value: value
    command: ["bash", "-c", "apt-get update && apt-get install -y sudo && apt-get install -y openssh-server nano && useradd -m $(USER) && echo '$(USER):$(PASSWORD)' | chpasswd && usermod -aG sudo $(USER) && service ssh start && tail -f /dev/null"]
    ports:
    - name: ssh
      containerPort: 22
      protocol: TCP
    - name: http
      containerPort: 80
      protocol: TCP
    resources:
      limits:
        memory: 2G
        cpu: "2"
      requests:
        memory: 2G
        cpu: "2"
