kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name:  monpvc-ubuntu
  labels:
    app: ubuntu-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G