apiVersion: v1
kind: Service
metadata:
  name: ubuntu-svc
  labels:
    app: ubuntu-app
spec:
  selector:
    app: ubuntu-app
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  - name: http
    port: 80
    targetPort: 80
  type: NodePort
